name: Run Tests

on:
    push:
        branches: [main, master, develop]
    pull_request:
        branches: [main, master, develop]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Cache pip packages
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Install Playwright browsers
              run: |
                  playwright install --with-deps chromium

            - name: Run API tests (test_sync.py)
              env:
                  TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
                  TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
              run: |
                  pytest tests/test_sync.py -v --tb=short
              continue-on-error: true

            - name: Run UI tests (test_trello_ui.py)
              env:
                  CI: 'true'
                  TRELLO_EMAIL: ${{ secrets.TRELLO_EMAIL }}
                  TRELLO_PASSWORD: ${{ secrets.TRELLO_PASSWORD }}
              run: |
                  pytest tests/test_trello_ui.py -v --tb=short
              continue-on-error: true

            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: |
                      .pytest_cache/
                  retention-days: 7
